### ISSUE TITLE
Thread local, `!Send + !Sync` version of `Event`

### ISSUE THREAD

**Issue by yshui** [smol-rs/event-listener#47]
Does it make sense to have a `!Send + !Sync` version of `Event`, to be used with `LocalExecutor`? Feels silly to pay the cost of thread synchronization when everything is happening on a single thread.

(and also a thread local version of `Mutex` and `RwLock`, which IIUC is based on `event_listener`?)

**Comment by notgull** [comment]
Previously, I was working on a thread-unsafe async framework called [`unsend`](https://github.com/notgull/unsend), which had thread unsafe versions of most of `smol`'s primitives. I stopped developing because I heard that Rust was moving towards adding `!Send + !Sync` versions of `Waker`, and if they did that it would change up my model considerably.

That being said, `smol` is intended to be thread-safe. Barring some kind of crazy generic solution, I don't see us moving forward on this.

**Comment by yshui** [comment]
> I heard that Rust was moving towards adding !Send + !Sync versions of Waker

Do you mean this: https://github.com/rust-lang/libs-team/issues/191 ?

**Comment by yshui** [comment]
> smol is intended to be thread-safe.

If this is the case, maybe `LocalExecutor` shouldn't be included either?

**Comment by notgull** [comment]
I've released `unsend` version 0.1.0, with an [`Event`](https://docs.rs/unsend/latest/unsend/struct.Event.html) structure similar to the one in this crate, but is `!Sync` and doesn't use any synchronization primitives.

Since we are not planning on adding an equivalent structure to `EventListener`, I'll close this issue now.

> If this is the case, maybe `LocalExecutor` shouldn't be included either?

`LocalExecutor` is a special case I feel, because most contemporary async runtimes (even thread-safe ones) provide a `LocalExecutor` analogue.
